### PR TITLE
Nip16

### PR DESCRIPTION
**Pull request by thesimplekid**
Adds support for for [NIP16](https://github.com/nostr-protocol/nips/blob/master/16.md). This does require that each time an event its call a request is made to the relay to get supported nips. It maybe better to do this once and cache it to avoid making unnecessary calls to the relay.  One way to do this is change `HashMap<String, Arc<Mutex<SimplifiedWS>>>`, to `HashMap<String, (Arc<Mutex<SimplifiedWS>>>, RelayInformationDocument)` and request the document once when the relay is added. https://github.com/0xtlt/nostr_rust/blob/31488762245982ddd6ff9dc179ed2bcd3c8e7320/src/nostr_client.rs#L30 

Wanted to see if you had any better ideas here before making changes. I'll leave this as a draft as it also depends one #19 an #20 changes.

### CODE REVIEW

**Comment by thesimplekid** [comment]
or maybe create a `Relay` struct and make `relays` a `Vec<relay>` instead of a Hasmap

**Comment by 0xtlt** [comment]
I don’t have much time right now but I’m going to look to think together in the next few days 👍

**Comment by 0xtlt** [comment]
Otherwise for the part of the relays document infos, I had already thought of putting it « cached » and I think it’s a good idea, we could add a default and configurable cache time 🤔

**Comment by 0xtlt** [comment]
Seems good but I think about automatically updating the kind in functions like `publish_ephemeral_event` to have the wanted kind directly like 1 will be automatically updated as 20001

To have more readable code

**Comment by 0xtlt** [comment]
What do you think?

**Comment by thesimplekid** [comment]
Good idea, just updated it much cleaner

**Comment by 0xtlt** [comment]
Now we just need to add this explanation in the comments to prevent developers from writing the wrong kind of code

**Pull request merged**
